### ISSUE TITLE
Error in showcase seeds

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/sprout#12]
A complete database reset works okay, but just re-running the seed file causes this error:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/300/157760744-4dcb007b-df5f-4240-99bc-5c28c8c108e3.png">

**Comment by noire-munich** [comment]
uuuh
Ok, I surrender, will send fix and move on

**Comment by noire-munich** [comment]
@cannikin Fixed it and forgot to report...
Do you still have the issue?
