### ISSUE TITLE
Update the navbar's positioning

### ISSUE THREAD

**Issue by realStandal** [redwoodjs/sprout#13]
Right now, the site's top navigation bar is `fixed`, so it doesn't take up space in the document. To compliment this, and mitigate each page/layout having its own offset, a fake navigation bar should be added which takes up the same amount of space as the navbar, pushing content down uniformly.

- [ ] - Update all pages and layouts to remove padding/margin used to offset for the navbar (where applicable).
- [ ] - Update [the navbar's](https://github.com/redwoodjs/sprout/blob/8b1eafcad921f1172a18a76b2b6593665b3946c5/web/src/layouts/MainLayout/MainLayout.tsx#L46) position from `fixed` to `sticky top-0`.

**Comment by cannikin** [comment]
Hmm, any reason not to just add margin to the top of the `<main>` element in the layout? I think I did it individually in the home and jobs pages because I didn't want to mess up the layout in other sections, but really it should just be a `mt-16` on the `<main>` element in `MainLayout.tsx` and then everyone gets that positioning for free.

With all the modern layout tools now you usually don't have to add arbitrary HTML just to move things around, you can almost alway accomplish the same thing on the existing semantic tags that are already on the page!

**Comment by realStandal** [comment]
@cannikin However it gets done, it gets done - I'm impartial! I just wanted the issue documented and noticed the two checklist items as needing to be taken care of.

No reason _not_ to (certainly the simpler option), my reasoning for adding an element is to decouple. Instead of the navigation bar and page content (wrapper, in this case) being tied together, the former can be extracted out into a component while the latter is just placed in the document as-is. `aria-hidden="true"` would work fine to hide the element and not trip out screen readers.

**Comment by realStandal** [comment]
I took a peek at [HeadlessUI's](https://headlessui.dev/) navbar, which functions the same as what we're aiming for Redwood's. They're using `sticky top-0` on the `<header>` to get the same effect with no extra elements or padding/margin offsets. (we should leave this to the professionals 😆)

So [our equivalent](https://github.com/redwoodjs/sprout/blob/8b1eafcad921f1172a18a76b2b6593665b3946c5/web/src/layouts/MainLayout/MainLayout.tsx#L46) should be able to go from `fixed` to `sticky top-0` with no need to offset on `<main>` or create a new element.

**Comment by cannikin** [comment]
Depending on what the designer comes up with we may not even have a sticky header any more! You can change it if you want, but it may all be for naught!

**Comment by KrisCoulson** [comment]
Just a heads up I have some updates coming to the navbar with the new design work so this should get resolved.
