### ISSUE TITLE
Enable brotli on CDN

### ISSUE THREAD

**Issue by pavelloz** [redwoodjs/sprout#38]
Hello,

It seems like you use cloudfront as your cdn, which have brotli compression built-in:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/546845/161880817-7b9256db-b49f-4e01-a772-6ed746a399c0.png">

This toggle is in edit cache policy settings that you attached to CF distribution.

Breadcrumb:
```
CloudFront
Policies
Cache
[uuid]
Edit cache policy
```

This change should shave off couple KBs on text assets like js/css/svg. Its not much, but its honest gain :-)

**Comment by thedavidprice** [comment]
We're deploying on Netlify. I was surprised but also noticed Cloudflare in our network.

@cannikin @dthyresson do you know how/where/why our web assets are on Cloudflare? Something new with Netlify?

**Comment by cannikin** [comment]
CloudFlare or Cloudfront? Netlify is on AWS so I assume Cloudfront, correct?

Yeah we don't have access to any of the underlying Cloudfront config, just these options exposed in the Netlify UI, and we've got 'em all turned on!

<img width="938" alt="image" src="https://user-images.githubusercontent.com/300/162089971-8abb7a2c-8a27-4284-a216-6bcb83d2a0ef.png">

**Comment by cannikin** [comment]
CloudFlare or Cloudfront? Netlify is on AWS so I assume Cloudfront, correct?

Yeah we don't have access to any of the underlying Cloudfront config, just these options exposed in the Netlify UI, and we've got 'em all turned on!

<img width="938" alt="image" src="https://user-images.githubusercontent.com/300/162089971-8abb7a2c-8a27-4284-a216-6bcb83d2a0ef.png">

**Comment by thedavidprice** [comment]
Lulz... Strike ~Cloudflare~. Indeed Cloudfront.

Need. Sleep. 💤

I'll close this out. Thanks again @pavelloz

**Comment by thedavidprice** [comment]
Oh, one more thing — 2 years ago when we launched the original site (notably _not_ on RedwoodJS), the Twitterati hammered us about our terrible Lighthouse scores (i.e. _not_ straight 100's). 

Two years later and @pavelloz  comes along and a) doesn't rip our Lighthouse performance but instead b) drops a monster PR — my faith in open source collaboration is restored!

Thank you 🙏

**Comment by pavelloz** [comment]
One way of going about it (and probably the best one too) would be to move all the assets to netlify and skip CF altogether - it would:
1) enable brotli (because netlify supports it by default)
2) eliminate one SSL handshake from the critical rendering chain, meaning core web vitals should improve, at least a little bit

PS. Thank you for your kind words. I have some more things cooking, that will hopefully help with frontend performance.

**Comment by cannikin** [comment]
@pavelloz I'm not sure what you mean—we don't send anything to Cloudfront ourselves. Netlify checks out our code and does whatever it does with the assets. If they're on Cloudfront then Netlify is putting them there! 🙂

**Comment by pavelloz** [comment]
Ouh, i just found information why netlify sometimes serve assets from cloudfront - its the assets optimization feature.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/546845/162324092-b77dec4a-2589-4f7c-a139-11f6e400f0f5.png">

Lets go one by one:
CSS bundling - you have that covered by redwood (webpack), probably much better than just concatenating multiple css files into one (http2 ftw)
CSS minify - that too i assume is done during build time, so not needed at all
JS bundling - same as CSS, but probably even better done by webpack. This setting i would consider harmful for SPAs 
JS minify - again, webpack does this
Images - since https://github.com/redwoodjs/sprout/pull/37 is merged, there is very slim chance that this is actually doing any favors

I would turn off everything regarding assets, and that would make assets to be served from netlify.com entirely, bringing couple benefits mentioned in [my previous comment.](https://github.com/redwoodjs/sprout/issues/38#issuecomment-1090973163)

**Comment by cannikin** [comment]
All right, here's the new settings:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/300/162325621-2b7325b4-6aa0-4427-bca7-8e639f30a59f.png">

**Comment by cannikin** [comment]
All right, here's the new settings:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/300/162325621-2b7325b4-6aa0-4427-bca7-8e639f30a59f.png">

**Comment by pavelloz** [comment]
It worked :) 

Heres the comparison before/after, it looks like its a lot better. Improvement per minute is amazing with this one :)
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/546845/162390713-c01fd884-3635-4204-810c-e9ff6d86b44f.png">
Source: [Tests](https://www.webpagetest.org/video/compare.php?tests=220408_AiDc4X_5S1,220407_AiDc47_P6)

Even though main image is loaded as 47th resource (more on the subject https://github.com/redwoodjs/sprout/pull/39 ).

For some reason half of the svgs are still loaded from cloudfront, but maybe some cache manifest needs to be cleared on netlify side, lets keep an eye on it. 

PS. Is the pretty url needed? Maybe disabling the whole thing would fix those 37 SVGs that are still loaded from CF.

**Comment by cannikin** [comment]
I'll try turning it off, let's see! I also did a "clear cache and deploy" so it should really start from scratch.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/300/162471553-4513611c-6f0f-47b3-a873-b5ac4f0d1bf2.png">

**Comment by cannikin** [comment]
I'll try turning it off, let's see! I also did a "clear cache and deploy" so it should really start from scratch.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/300/162471553-4513611c-6f0f-47b3-a873-b5ac4f0d1bf2.png">

**Comment by pavelloz** [comment]
Well, first paint is good to have asap, but largest contentful paint is also very important. And thats what im trying to fix ATM with this recommendation + tackling hero image priority.
